config/routes.rb
Backlist::Application.routes.draw do
  resources :zutats

  resources :termins

  resources :rezepts

  resources :einzelbewertungs

  resources :bewertungs

  resources :benutzers

end

app/models/termin.rb
class Termin < ActiveRecord::Base
  attr_accessible :benutzer_id, :beschreibung, :datum
  belongs_to :benutzer
end

app/controllers/termins_controller.rb
class TerminsController < ApplicationController
  # GET /termins
  # GET /termins.json
  def index
    @termins = Termin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @termins }
    end
  end

  # GET /termins/1
  # GET /termins/1.json
  def show
    @termin = Termin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @termin }
    end
  end

  # GET /termins/new
  # GET /termins/new.json
  def new
    @termin = Termin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @termin }
    end
  end

  # GET /termins/1/edit
  def edit
    @termin = Termin.find(params[:id])
  end

  # POST /termins
  # POST /termins.json
  def create
    @termin = Termin.new(params[:termin])

    respond_to do |format|
      if @termin.save
        format.html { redirect_to @termin, notice: 'Termin was successfully created.' }
        format.json { render json: @termin, status: :created, location: @termin }
      else
        format.html { render action: "new" }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /termins/1
  # PUT /termins/1.json
  def update
    @termin = Termin.find(params[:id])

    respond_to do |format|
      if @termin.update_attributes(params[:termin])
        format.html { redirect_to @termin, notice: 'Termin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /termins/1
  # DELETE /termins/1.json
  def destroy
    @termin = Termin.find(params[:id])
    @termin.destroy

    respond_to do |format|
      format.html { redirect_to termins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/termins_helper.rb
module TerminsHelper
end

app/views/termins/_form.html.erb
<%= form_for(@termin) do |f| %>
  <% if @termin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@termin.errors.count, "error") %> prohibited this termin from being saved:</h2>

      <ul>
      <% @termin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datum %><br />
    <%= f.datetime_select :datum %>
  </div>
  <div class="field">
    <%= f.label :beschreibung %><br />
    <%= f.text_field :beschreibung %>
  </div>
  <div class="field">
    <%= f.label :benutzer_id %><br />
    <%= f.text_field :benutzer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/termins/edit.html.erb
<h1>Editing termin</h1>

<%= render 'form' %>

<%= link_to 'Show', @termin %> |
<%= link_to 'Back', termins_path %>

app/views/termins/index.html.erb
<h1>Listing termins</h1>

<table>
  <tr>
    <th>Datum</th>
    <th>Beschreibung</th>
    <th>Benutzer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @termins.each do |termin| %>
  <tr>
    <td><%= termin.datum %></td>
    <td><%= termin.beschreibung %></td>
    <td><%= termin.benutzer_id %></td>
    <td><%= link_to 'Show', termin %></td>
    <td><%= link_to 'Edit', edit_termin_path(termin) %></td>
    <td><%= link_to 'Destroy', termin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Termin', new_termin_path %>

app/views/termins/new.html.erb
<h1>New termin</h1>

<%= render 'form' %>

<%= link_to 'Back', termins_path %>

app/views/termins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Datum:</b>
  <%= @termin.datum %>
</p>

<p>
  <b>Beschreibung:</b>
  <%= @termin.beschreibung %>
</p>

<p>
  <b>Benutzer:</b>
  <%= @termin.benutzer_id %>
</p>


<%= link_to 'Edit', edit_termin_path(@termin) %> |
<%= link_to 'Back', termins_path %>