config/routes.rb
Backlist::Application.routes.draw do
  resources :zutats

  resources :termins

  resources :rezepts

  resources :einzelbewertungs

  resources :bewertungs

  resources :benutzers

end

app/models/zutat.rb
class Zutat < ActiveRecord::Base
  attr_accessible :rezept_id, :text
  belongs_to :rezept
end

app/controllers/zutats_controller.rb
class ZutatsController < ApplicationController
  # GET /zutats
  # GET /zutats.json
  def index
    @zutats = Zutat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zutats }
    end
  end

  # GET /zutats/1
  # GET /zutats/1.json
  def show
    @zutat = Zutat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zutat }
    end
  end

  # GET /zutats/new
  # GET /zutats/new.json
  def new
    @zutat = Zutat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zutat }
    end
  end

  # GET /zutats/1/edit
  def edit
    @zutat = Zutat.find(params[:id])
  end

  # POST /zutats
  # POST /zutats.json
  def create
    @zutat = Zutat.new(params[:zutat])

    respond_to do |format|
      if @zutat.save
        format.html { redirect_to @zutat, notice: 'Zutat was successfully created.' }
        format.json { render json: @zutat, status: :created, location: @zutat }
      else
        format.html { render action: "new" }
        format.json { render json: @zutat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zutats/1
  # PUT /zutats/1.json
  def update
    @zutat = Zutat.find(params[:id])

    respond_to do |format|
      if @zutat.update_attributes(params[:zutat])
        format.html { redirect_to @zutat, notice: 'Zutat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zutat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zutats/1
  # DELETE /zutats/1.json
  def destroy
    @zutat = Zutat.find(params[:id])
    @zutat.destroy

    respond_to do |format|
      format.html { redirect_to zutats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/zutats_helper.rb
module ZutatsHelper
end

app/views/zutats/_form.html.erb
<%= form_for(@zutat) do |f| %>
  <% if @zutat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zutat.errors.count, "error") %> prohibited this zutat from being saved:</h2>

      <ul>
      <% @zutat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :rezept_id %><br />
    <%= f.text_field :rezept_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zutats/edit.html.erb
<h1>Editing zutat</h1>

<%= render 'form' %>

<%= link_to 'Show', @zutat %> |
<%= link_to 'Back', zutats_path %>

app/views/zutats/index.html.erb
<h1>Listing zutats</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Rezept</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zutats.each do |zutat| %>
  <tr>
    <td><%= zutat.text %></td>
    <td><%= zutat.rezept_id %></td>
    <td><%= link_to 'Show', zutat %></td>
    <td><%= link_to 'Edit', edit_zutat_path(zutat) %></td>
    <td><%= link_to 'Destroy', zutat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zutat', new_zutat_path %>

app/views/zutats/new.html.erb
<h1>New zutat</h1>

<%= render 'form' %>

<%= link_to 'Back', zutats_path %>

app/views/zutats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @zutat.text %>
</p>

<p>
  <b>Rezept:</b>
  <%= @zutat.rezept_id %>
</p>


<%= link_to 'Edit', edit_zutat_path(@zutat) %> |
<%= link_to 'Back', zutats_path %>