config/routes.rb
Backlist::Application.routes.draw do
  resources :zutats

  resources :termins

  resources :rezepts

  resources :einzelbewertungs

  resources :bewertungs

  resources :benutzers

end

app/models/bewertung.rb
class Bewertung < ActiveRecord::Base
  attr_accessible :rezept_id, :text
  belongs_to :rezept
  has_many :einzelbewertung
end

app/controllers/bewertungs_controller.rb
class BewertungsController < ApplicationController
  # GET /bewertungs
  # GET /bewertungs.json
  def index
    @bewertungs = Bewertung.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bewertungs }
    end
  end

  # GET /bewertungs/1
  # GET /bewertungs/1.json
  def show
    @bewertung = Bewertung.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bewertung }
    end
  end

  # GET /bewertungs/new
  # GET /bewertungs/new.json
  def new
    @bewertung = Bewertung.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bewertung }
    end
  end

  # GET /bewertungs/1/edit
  def edit
    @bewertung = Bewertung.find(params[:id])
  end

  # POST /bewertungs
  # POST /bewertungs.json
  def create
    @bewertung = Bewertung.new(params[:bewertung])

    respond_to do |format|
      if @bewertung.save
        format.html { redirect_to @bewertung, notice: 'Bewertung was successfully created.' }
        format.json { render json: @bewertung, status: :created, location: @bewertung }
      else
        format.html { render action: "new" }
        format.json { render json: @bewertung.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bewertungs/1
  # PUT /bewertungs/1.json
  def update
    @bewertung = Bewertung.find(params[:id])

    respond_to do |format|
      if @bewertung.update_attributes(params[:bewertung])
        format.html { redirect_to @bewertung, notice: 'Bewertung was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bewertung.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bewertungs/1
  # DELETE /bewertungs/1.json
  def destroy
    @bewertung = Bewertung.find(params[:id])
    @bewertung.destroy

    respond_to do |format|
      format.html { redirect_to bewertungs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bewertungs_helper.rb
module BewertungsHelper
end

app/views/bewertungs/_form.html.erb
<%= form_for(@bewertung) do |f| %>
  <% if @bewertung.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bewertung.errors.count, "error") %> prohibited this bewertung from being saved:</h2>

      <ul>
      <% @bewertung.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :rezept_id %><br />
    <%= f.text_field :rezept_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bewertungs/edit.html.erb
<h1>Editing bewertung</h1>

<%= render 'form' %>

<%= link_to 'Show', @bewertung %> |
<%= link_to 'Back', bewertungs_path %>

app/views/bewertungs/index.html.erb
<h1>Listing bewertungs</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Rezept</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bewertungs.each do |bewertung| %>
  <tr>
    <td><%= bewertung.text %></td>
    <td><%= bewertung.rezept_id %></td>
    <td><%= link_to 'Show', bewertung %></td>
    <td><%= link_to 'Edit', edit_bewertung_path(bewertung) %></td>
    <td><%= link_to 'Destroy', bewertung, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bewertung', new_bewertung_path %>

app/views/bewertungs/new.html.erb
<h1>New bewertung</h1>

<%= render 'form' %>

<%= link_to 'Back', bewertungs_path %>

app/views/bewertungs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @bewertung.text %>
</p>

<p>
  <b>Rezept:</b>
  <%= @bewertung.rezept_id %>
</p>


<%= link_to 'Edit', edit_bewertung_path(@bewertung) %> |
<%= link_to 'Back', bewertungs_path %>