config/routes.rb
Backlist::Application.routes.draw do
  resources :zutats

  resources :termins

  resources :rezepts

  resources :einzelbewertungs

  resources :bewertungs

  resources :benutzers

end

app/models/einzelbewertung.rb
class Einzelbewertung < ActiveRecord::Base
  attr_accessible :bewertung_id, :typ, :wert
  belongs_to :bewertung
end

app/controllers/einzelbewertungs_controller.rb
class EinzelbewertungsController < ApplicationController
  # GET /einzelbewertungs
  # GET /einzelbewertungs.json
  def index
    @einzelbewertungs = Einzelbewertung.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @einzelbewertungs }
    end
  end

  # GET /einzelbewertungs/1
  # GET /einzelbewertungs/1.json
  def show
    @einzelbewertung = Einzelbewertung.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @einzelbewertung }
    end
  end

  # GET /einzelbewertungs/new
  # GET /einzelbewertungs/new.json
  def new
    @einzelbewertung = Einzelbewertung.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @einzelbewertung }
    end
  end

  # GET /einzelbewertungs/1/edit
  def edit
    @einzelbewertung = Einzelbewertung.find(params[:id])
  end

  # POST /einzelbewertungs
  # POST /einzelbewertungs.json
  def create
    @einzelbewertung = Einzelbewertung.new(params[:einzelbewertung])

    respond_to do |format|
      if @einzelbewertung.save
        format.html { redirect_to @einzelbewertung, notice: 'Einzelbewertung was successfully created.' }
        format.json { render json: @einzelbewertung, status: :created, location: @einzelbewertung }
      else
        format.html { render action: "new" }
        format.json { render json: @einzelbewertung.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /einzelbewertungs/1
  # PUT /einzelbewertungs/1.json
  def update
    @einzelbewertung = Einzelbewertung.find(params[:id])

    respond_to do |format|
      if @einzelbewertung.update_attributes(params[:einzelbewertung])
        format.html { redirect_to @einzelbewertung, notice: 'Einzelbewertung was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @einzelbewertung.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /einzelbewertungs/1
  # DELETE /einzelbewertungs/1.json
  def destroy
    @einzelbewertung = Einzelbewertung.find(params[:id])
    @einzelbewertung.destroy

    respond_to do |format|
      format.html { redirect_to einzelbewertungs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/einzelbewertungs_helper.rb
module EinzelbewertungsHelper
end

app/views/einzelbewertungs/_form.html.erb
<%= form_for(@einzelbewertung) do |f| %>
  <% if @einzelbewertung.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@einzelbewertung.errors.count, "error") %> prohibited this einzelbewertung from being saved:</h2>

      <ul>
      <% @einzelbewertung.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typ %><br />
    <%= f.text_field :typ %>
  </div>
  <div class="field">
    <%= f.label :wert %><br />
    <%= f.text_field :wert %>
  </div>
  <div class="field">
    <%= f.label :bewertung_id %><br />
    <%= f.text_field :bewertung_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/einzelbewertungs/edit.html.erb
<h1>Editing einzelbewertung</h1>

<%= render 'form' %>

<%= link_to 'Show', @einzelbewertung %> |
<%= link_to 'Back', einzelbewertungs_path %>

app/views/einzelbewertungs/index.html.erb
<h1>Listing einzelbewertungs</h1>

<table>
  <tr>
    <th>Typ</th>
    <th>Wert</th>
    <th>Bewertung</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @einzelbewertungs.each do |einzelbewertung| %>
  <tr>
    <td><%= einzelbewertung.typ %></td>
    <td><%= einzelbewertung.wert %></td>
    <td><%= einzelbewertung.bewertung_id %></td>
    <td><%= link_to 'Show', einzelbewertung %></td>
    <td><%= link_to 'Edit', edit_einzelbewertung_path(einzelbewertung) %></td>
    <td><%= link_to 'Destroy', einzelbewertung, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Einzelbewertung', new_einzelbewertung_path %>

app/views/einzelbewertungs/new.html.erb
<h1>New einzelbewertung</h1>

<%= render 'form' %>

<%= link_to 'Back', einzelbewertungs_path %>

app/views/einzelbewertungs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Typ:</b>
  <%= @einzelbewertung.typ %>
</p>

<p>
  <b>Wert:</b>
  <%= @einzelbewertung.wert %>
</p>

<p>
  <b>Bewertung:</b>
  <%= @einzelbewertung.bewertung_id %>
</p>


<%= link_to 'Edit', edit_einzelbewertung_path(@einzelbewertung) %> |
<%= link_to 'Back', einzelbewertungs_path %>